[package]
name = "isaac_tears"
version = "0.1.0"
authors = ["Chris Janaqi <chris.janaqi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.3"
ggez = "0.5"

[profile.dev]
opt-level = 1
